export {
  EXERCISE_PACKS,
  ENDPOINTS,
  normalizeExercisePackId,
  listExercisePacks,
  getExercisePackById,
  getPackDefaults,
  getAllowedCanvasTypesForPack,
  getDefaultCanvasTypeIdForPack,
  listExerciseSteps,
  getExerciseStep,
  getDefaultStepId,
  getNextExerciseStep,
  getDefaultEnterTrigger,
  listStepTransitions,
  resolveNamedTransition,
  listEndpointsForPack,
  listStepEndpoints,
  listStepEndpointsForSurface,
  getEndpointById,
  findStepEndpointByTriggerKey,
  listStepTriggerKeysFromEndpoints,
  isSidecarOnlyEndpoint
} from "./method-catalog.js?v=20260312-patch11";
